# Generated by Django 4.1.4 on 2023-06-09 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def associate_with_first_user(apps, schema_editor):
    Document = apps.get_model('accounts', 'Document')
    User = apps.get_model('auth', 'User')
    first_user = User.objects.first()
    Document.objects.filter(user__isnull=True).update(user=first_user)

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_document'),
    ]

    operations = [
        migrations.RunPython(associate_with_first_user),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
